### ISSUE TITLE
HOw can use this library in iOS App

### ISSUE THREAD

**Issue by gafurcseku** [underthestars-zhy/MagicData#3]
Please share process of use this library.

**Comment by underthestars-zhy** [comment]
By adding the URL to the swift package manage.
![CleanShot 2022-06-13 at 20 16 23@2x](https://user-images.githubusercontent.com/46642225/173351550-1e425688-7f77-4d40-b6f1-eee070ce8b26.png)
<img width="617" alt="CleanShot 2022-06-13 at 20 16 49@2x" src="https://user-images.githubusercontent.com/46642225/173351605-48e5708a-c810-422c-b52b-dec95729760b.png">

**Comment by underthestars-zhy** [comment]
But maybe you should wait for some days to use it. Because there will be a lot of changes before the first version is released.
